# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  paddle-surf-app:
    build:
      target: development
    image: paddle-surf-app-development
    container_name: paddle-surf-app-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
