services:
  paddle-surf-app:
    build:
      context: .
      target: production
    image: paddle-surf-app
    container_name: paddle-surf-app
    environment:
      APPINSIGHTS_CLOUDROLE: paddle-surf-app-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
