{{- include "ffc-helm-library.container-secret" (list . "paddle-surf-app.container-secret") -}}
{{- define "paddle-surf-app.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
